### Variables
@serverIp = http://localhost
@serverPort = 53188
@serverAddress = {{serverIp}}:{{serverPort}}
@token = {{login.response.body.$.token}}
@refreshToken = {{login.response.body.$.refreshToken}}
@userEmail = harry@harry.com
@userId = {{getUserByEmail.response.body.$.id}}
@entryId = d6c3c840-aab4-49bd-8ec3-728f0641d549
@commentId = xxx


### -------------------- Account --------------------

### Register
POST {{serverAddress}}/api/accounts/register
Content-Type: application/json

{
    "email": "harry@harry.com",
    "userName": "Harry",
    "password": "password"
}

### Login
# @name login
POST {{serverAddress}}/api/accounts/login
Content-Type: application/json

{
    "email": "harry@harry.com",
    "password": "password"
}

### Get user by id
GET {{serverAddress}}/api/accounts/user/byId/{{userId}}

### Get user by email
# @name getUserByEmail
GET {{serverAddress}}/api/accounts/user/byEmail/{{userEmail}}

### Refresh access token
GET {{serverAddress}}/api/accounts/tokens/refresh/{{refreshToken}}

### Revoke refresh token
GET {{serverAddress}}/api/accounts/tokens/revoke/{{refreshToken}}

### -------------------- Entries --------------------
### Get entries
GET {{serverAddress}}/api/entries/newest?currentPage=0&limitPerPage=2
Authorization: Bearer {{token}}

### Get entry
GET {{serverAddress}}/api/entries/{{entryId}}
Authorization: Bearer {{token}}

### Add entry
POST {{serverAddress}}/api/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "tedsadxt23ff2"
}

### Delete entry
DELETE {{serverAddress}}/api/entries/{{entryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### -------------------- Comments --------------------
### Get comment
GET {{serverAddress}}/api/comments/{{commentId}}
Authorization: Bearer {{token}}

### Get comments for entry
GET {{serverAddress}}/api/comments/entry/{{entryId}}
Authorization: Bearer {{token}}

### Add comment
POST {{serverAddress}}/api/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "entryId": "{{entryId}}",
    "text": "messag22e"
}

### Delete comment
DELETE {{serverAddress}}/api/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### -------------------- Karma --------------------

### -------- Entry --------
### Upvote entry
GET {{serverAddress}}/api/karma/entry/upvote/{{entryId}}
Authorization: Bearer {{token}}

### Downvote entry
GET {{serverAddress}}/api/karma/entry/downvote/{{entryId}}
Authorization: Bearer {{token}}

### Remove vote
DELETE {{serverAddress}}/api/karma/entry/remove/{{entryId}}
Authorization: Bearer {{token}}

### Count karma
GET {{serverAddress}}/api/karma/entry/count/{{entryId}}

### Get user vote
GET {{serverAddress}}/api/karma/entry/?userId={{userId}}&itemId={{entryId}}

### -------- Comment --------
### Upvote comment
GET {{serverAddress}}/api/karma/comment/upvote/{{commentId}}
Authorization: Bearer {{token}}

### Downvote comment
GET {{serverAddress}}/api/karma/comment/downvote/{{commentId}}
Authorization: Bearer {{token}}

### Remove comment
DELETE {{serverAddress}}/api/karma/comment/remove/{{commentId}}
Authorization: Bearer {{token}}

### Count karma
GET {{serverAddress}}/api/karma/comment/count/{{commentId}}

### Get user vote
GET {{serverAddress}}/api/karma/comment/?userId={{userId}}&itemId={{commentId}}